networks:
  edgex-network:
    driver: bridge
services:
  mock-device:
    build: mqtt-scripts-2-dev
    command: --url mqtt://192.168.1.152 --dir /app/scripts
    container_name: mqtt-scripts
    networks:
    - edgex-network
    restart: always
version: "3.6"
